[package]
name = "homados"
version = "0.0.3"
edition = "2024"
authors = ["conner"]
description = "Signal should be simple."
readme = "README.md"
license-file = "License.md"

[dependencies]
rand = "0.9.0"
rand_distr = "0.5.1"
hound = "3.5.1"
clap = { version = "4.5.31", features = ["derive"] }
